server:
  port: 8169
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8167/eureka/

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: api-structured-output-service
              uri: lb://api-structured-output-service
              predicates:
                - Path=/api/openai/structured-output/**
            - id: api-text-generation-service
              uri: lb://api-text-generation-service
              predicates:
                - Path=/api/openai/text-generation/**
            - id: api-audio-speech-service
              uri: lb://api-audio-speech-service
              predicates:
                - Path=/api/openai/audio-speech/**
            - id: api-audio-speech-ws
              uri: lb://api-audio-speech-service
              predicates:
                - Path=/ws/voice
            - id: api-images-vision-service
              uri: lb://api-images-vision-service
              predicates:
                - Path=/api/openai/images-vision/**